-- -----------------------------------------------------
-- Schema pcstore-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pcstore-ecommerce`;

CREATE SCHEMA `pcstore-ecommerce`;
USE `pcstore-ecommerce` ;

-- -----------------------------------------------------
-- Table `pcstore-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcstore-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table 'pcstore-ecommerce'.'product'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcstore-ecommerce`.`product`(
`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
`bar_code` VARCHAR(255) DEFAULT NULL,
`name` VARCHAR(255) DEFAULT NULL,
`description` VARCHAR(255) DEFAULT NULL,
`unit_price` DECIMAL(13,2) DEFAULT NULL,
`image_url` VARCHAR(255) DEFAULT NULL,
`active` BIT DEFAULT 1,
`units_in_stock` INT(11) DEFAULT NULL,
`date_created` DATETIME(6) DEFAULT NULL,
`last_updated` DATETIME(6) DEFAULT NULL,
`category_id` BIGINT(20) NOT NULL,
PRIMARY KEY (`id`),
KEY `fk_category` (`category_id`),
CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT =1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('Laptops');
INSERT INTO product_category(category_name) VALUES ('Pcs');
INSERT INTO product_category(category_name) VALUES ('Graphic Cards');
INSERT INTO product_category(category_name) VALUES ('Processors');
INSERT INTO product_category(category_name) VALUES ('Ram');
INSERT INTO product_category(category_name) VALUES ('Monitors');

-- -----------------------------------------------------
-- Laptops
-- -----------------------------------------------------
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1000','MSI Stealth 15M Gaming Laptop','15.6" 144Hz FHD 1080p Display, Intel Core i7-11375H, NVIDIA GeForce RTX 3060, 16GB, 512GB SSD, Thunderbolt 4, WiFi 6, Win10, Carbon Gray (A11UEK-009)',1189.99,'assets/images/products/laptops/laptop-1000.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1001','ASUS TUF Gaming F15 (2022) Gaming Laptop"','15.6” 300Hz FHD Display, Intel Core i7-12700H, GeForce RTX 3060, 16GB DDR5, 1TB PCIe SSD, Thunderbolt 4, Wi-Fi 6, Windows 11 Home, Mecha Gray, FX507ZM-ES74 ',1446.88,'assets/images/products/laptops/laptop-1001.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1002','Acer Predator Helios 300 Gaming Laptop','Intel i7-10750H, NVIDIA GeForce RTX 3060 Laptop GPU, 15.6" Full HD 144Hz 3ms IPS Display, 16GB DDR4, 512GB NVMe SSD, WiFi 6, RGB Keyboard, PH315-53-71HN',1499.99,'assets/images/products/laptops/laptop-1002.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1003','ASUS ROG Strix G17 Gaming Laptop, 17.3"','FHD IPS 144 Hz Display, AMD Ryzen 7 4800H 8-Core, NVIDIA GeForce RTX 3060 6GB GDDR6, Wi-Fi 6, RGB Keyboard, USB-C, HDMI, Win 10 (16GB RAM | 1TB PCIe SSD) ',1519.88,'assets/images/products/laptops/laptop-1003.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1004','ASUS ROG Strix Scar 15 (2022) Gaming Laptop','15.6” 240Hz IPS QHD Display, NVIDIA GeForce RTX 3080 Ti, Intel Core i9 12900H, 32GB DDR5, 1TB SSD, Per-Key RGB Keyboard, Windows 11 Pro, G533ZX-XS96 ',3299.99,'assets/images/products/laptops/laptop-1004.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1005','2022 ASUS TUF FX706HE Gaming Laptop','17.3” 144Hz FHD IPS Display Intel 6-Core i5-11260H 16GB DDR4 1TB NVMe SSD NVIDIA GeForce RTX 3050Ti 4GB GDDR6 WiFi AX BT 5.2 RJ45 USB-C Backlit Windows 11 w/USB',1799,'assets/images/products/laptops/laptop-1005.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1006','GIGABYTE AERO 17 HDR XD - 17.3"','UHD 4k IPS Anti-Glare, Intel Core i7, NVIDIA GeForce RTX 3070 Laptop GPU 8GB GDDR6, 16GB RAM, 1TB SSD, Win10 Pro, Creator Laptop (AERO 17 HDR XD-73US524SP)',2499.99,'assets/images/products/laptops/laptop-1006.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1007','Acer Nitro 5 AN515 Gaming Laptop','Intel Core i5-10300H Up to 4.5GHz, NVIDIA GeForce RTX 3050 GPU, 15.6" FHD 144Hz IPS, 16GB DDR4, 1TB NVMe SSD, Intel Wi-Fi 6, Backlit Keyboard, TWE Cloth ',1215,'assets/images/products/laptops/laptop-1007.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1008','Razer Blade 14 Gaming Laptop','AMD Ryzen 9 5900HX 8 Core, NVIDIA GeForce RTX 3080, 14" QHD 165Hz, 16GB RAM, 1TB SSD - CNC Aluminum - Chroma RGB - THX Spatial Audio - Vapor Chamber Cooling',2649,'assets/images/products/laptops/laptop-1008.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1009','MSI GE76 Raider Gaming Laptop 2021','(1TB SSD, 16GB RAM) 17.3" FHD 144 Hz, Intel Core i7-1180H (11th Gen), NVIDIA GeForce RTX 3060, Windows 10 64bit (Titanium Blue) 11UE-046 US Model',1389.99,'assets/images/products/laptops/laptop-1009.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1010','MSI GS76 Stealth Gaming Laptop','17.3" 4K Display, Intel Core i9-11900H, NVIDIA GeForce RTX 3080, 64GB, 2TB SSD, Thunderbolt 4, WiFi 6, Win10, Black(11UH-078)',3849.99,'assets/images/products/laptops/laptop-1010.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1011','2021 MSI GF65 Gaming Laptop','15.6" FHD 144Hz IPS Display, Intel Six-Core i5-10500H Processor, NVIDIA GeForce RTX 3060 GDDR6, 32GB RAM, 1TB PCIe NVMe SSD, WiFi 6, Backlit KB, HDMI, Windows 10, Black',1299.99,'assets/images/products/laptops/laptop-1011.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1012','Lenovo Legion 5 Gaming Laptop','15.6" FHD Display, AMD Ryzen 7 5800H, 16GB RAM, 512GB Storage, NVIDIA GeForce RTX 3050Ti, Windows 10H, Phantom Blue',1299.00,'assets/images/products/laptops/laptop-1012.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1013','Acer Nitro 5 Gaming Laptop Full HD','9th Gen Intel Core i7-9750H, NVIDIA GeForce RTX 2060, 15.6" Full HD IPS 144Hz Display, 16GB DDR4, 256GB NVMe SSD, Wi-Fi 6, Waves MaxxAudio, Backlit Keyboard, AN515-54-728C',1199.99,'assets/images/products/laptops/laptop-1013.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1014','ASUS ProArt StudioBook 16 Laptop','16” 2560x1600 120Hz Display, AMD Ryzen 7, 32GB DDR4, 1TB PCIe SSD, Nvidia Geforce RTX 3060, Windows 11 Home, H5600QM-AH78, Star Black',1611.36,'assets/images/products/laptops/laptop-1014.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1015','ASUS ROG Zephyrus S17 (2022) Gaming Laptop','17.3” 165Hz WQHD, NVIDIA GeForce RTX 3080, Intel Core i9-11900H, 32GB DDR4, 1TB SSD, Per-Key RGB Keyboard, Thunderbolt 4, Windows 10 Pro, GX703HS-XH98',3199.00,'assets/images/products/laptops/laptop-1015.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1016','ASUS ROG Zephyrus 15.6" QHD','165Hz IPS Gaming Laptop,AMD Ryzen 9 5900HS, NVIDIA GeForce RTX 3070, Wi-Fi 6, RGB Keyboard, Bluetooth, Eclipse Grey + 32GB SD Card (16GB RAM | 1TB PCIe SSD)',1938.99,'assets/images/products/laptops/laptop-1016.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1017','Acer Nitro 5 Gaming Laptop 15.6"',' FHD 144Hz IPS Display, Intel Core i5-10300H Processor, NVIDIA GeForce RTX 3050, 32GB RAM, 2TB PCIe NVMe SSD, Backlit Keyboard, Windows 10 Home, Intel Wi-Fi 6 ',1379.00,'assets/images/products/laptops/laptop-1017.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1018','MSI GE76 Raider Gaming Laptop','Intel Core i7-11800H, GeForce RTX 3060, 17.3" FHD 144HZ, 32GB RAM2TB NVMe SSD, Wi-Fi6, Windows 10',1986.00,'assets/images/products/laptops/laptop-1018.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1019','Acer Nitro 5 AN517-41-R0RZ Gaming Laptop','AMD Ryzen 7 5800H (8-Core), NVIDIA GeForce RTX 3060 Laptop GPU, 17.3" FHD 144Hz IPS Display, 16GB DDR4, 1TB NVMe SSD, WiFi 6, RGB Backlit Keyboard',1540.00,'assets/images/products/laptops/laptop-1019.jpg',1,5,NOW(),1);
INSERT INTO product(bar_code, name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('LAPTOP-1019','MSI GF65 Gaming Laptop 15.6" ','144Hz FHD 1080p, Intel Core i7-10750H 6 Core, NVIDIA GeForce RTX 3060, 16GB, 512GB NVMe SSD, WiFi 6, Red Keyboard, Win 10, Black (10UE-047)',1348.00,'assets/images/products/laptops/laptop-1019.jpg',1,5,NOW(),1);

-- -----------------------------------------------------
-- PCS
-- -----------------------------------------------------
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1000','Gaming PC Desktop Computer by Alarco','Intel i5 3.10GHz,8GB Ram,1TB Hard Drive,Windows 10 pro,WiFi Ready,Video Card Nvidia GTX 650 1GB, 3 RGB Fans with Remote ',499.99,'assets/images/products/pcs/pc-1000.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1001','CYBERPOWERPC Gamer Xtreme VR Gaming','Intel Core i5-11600KF 3.9GHz, 16GB DDR4, GeForce RTX 3060 12GB, 500GB NVMe SSD, 1TB HDD, WiFi Ready & Win 11 Home (GXiVR8480A10) ',1199.99,'assets/images/products/pcs/pc-1001.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1002','CYBERPOWERPC Gamer Xtreme VR Gaming',' Intel Core i5-11400F 2.6GHz, 8GB DDR4, GeForce RTX 2060 6GB, 500GB NVMe SSD, WiFi Ready & Win 11 Home (GXiVR8060A11) ',1014.81,'assets/images/products/pcs/pc-1002.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1003','iBUYPOWER Pro Gaming PC Computer','Desktop Slate5MR 243i (Intel Core i7-11700F 2.5 GHz,AMD Radeon RX 6600 8GB, 16GB DDR4, 500GB SSD + 1 TB HDD, WiFi Ready, Windows 11 Home) ',1299.99,'assets/images/products/pcs/pc-1003.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1004','Alarco Gaming PC Desktop Computer','Intel i5 3.10GHz,8GB Ram,1TB Hard Drive,Windows 10 pro,WiFi Ready,Video Card Nvidia GTX 650 1GB, 6 RGB Fans with Remote',549.99,'assets/images/products/pcs/pc-1004.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1005','Acer Predator Orion 3000 PC','PO3-630-UA15 Gaming, 11th Gen Intel Core i7-11700F 8-Core, GeForce RTX 3070, 16GB DDR4, 512GB NVMe SSD, 1TB HDD, Wi-Fi 6, Windows 11 Home, RGB Keyboard & Mouse',999,'assets/images/products/pcs/pc-1005.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1006','SkyTech Archangel 3.0 Gaming Computer','Ryzen 5 3600 6-Core 3.6GHz, RTX 3060 12GB, 1TB SSD, 16GB DDR4 3200, RGB Fans, AC WiFi, 600W Gold PSU, Windows 10 Home 64-bit, White ',1399.99,'assets/images/products/pcs/pc-1006.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1007','Skytech Shadow Gaming PC Desktop','Intel Core i5 10400F 2.9 GHz, RTX 3050, 1TB NVME SSD, 8G DDR4 3200, 600W Gold PSU, AC Wi-Fi, Windows 10 Home 64-bit ',999.99,'assets/images/products/pcs/pc-1007.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1008','ROG Strix G10 Gaming PC ','Intel Core i7-11700, GeForce RTX 3060, 16GB DDR4 RAM, 1TB PCIe SSD, Wi-Fi 5, Windows 11 Home, G10CE-AH766',1499.99,'assets/images/products/pcs/pc-1008.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1009','HP Pavilion TG01 Gaming  PC','Intel Core i5-10400F 2.9GHz 12GB RAM 512GB SSD NVIDIA GeForce GTX 1650 Super 4GB GDDR6 Dedicated Graphics Windows 10 (Renewed) ',799.99,'assets/images/products/pcs/pc-1009.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1010','HP Pavilion Gaming Desktop','NVIDIA GeForce GTX 1650, Intel Core i5-10400F, 8 GB DDR4 RAM, 256 GB PCIe NVMe SSD, Windows 11, USB Mouse and Keyboard, Compact Tower Design (TG01-1020, 2020)',759.02,'assets/images/products/pcs/pc-1010.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1011','SkyTech Shadow Gaming Computer PC Desktop','Ryzen 5 3600 6-Core 3.6GHz, 1660 Super 6G, 1TB SSD, 16GB DDR4 3000, RGB Fans, AC WiFi, Windows 10 Home 64-bit, Black',1199.99,'assets/images/products/pcs/pc-1011.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1012','Thermaltake Graphite 360 Gaming PC','AMD Ryzen 5 5600X, RTX 3060, 16GB RGB 3200Mhz DDR4 ToughRAM RGB Memory, 1TB NVMe M.2, WiFi, Win 10 Home, Gaming Desktop Computer S1BK-B550-G36-LCS ',1599.99,'assets/images/products/pcs/pc-1012.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1013','Skytech Gaming Archangel Gaming','Computer PC Desktop – Ryzen 5 5600X 3.7GHz, RTX 3060 TI 8G, 1TB NVMe SSD, 16GB DDR4 3200MHz, RGB Fans, Windows 10 Home 64-bit, 802.11AC Wi-Fi, White',1699.99,'assets/images/products/pcs/pc-1013.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1014','Skytech Chronos Gaming PC Desktop','AMD Ryzen 5 5600X 3.7 GHz, RTX 3060, 1TB NVME SSD, 16G DDR4 3200, 600W Gold PSU, AC Wi-Fi, Windows 10 Home 64-bit ',1375.01,'assets/images/products/pcs/pc-1014.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1015','Onyx Gaming PC Desktop Computer','Intel i5 3.20GHz, 8GB RAM, 1TB Hard Drive, Windows 10 Pro, Wi-Fi Ready, Video Card NVidia GT 710 1GB, 3 RGB Fans with Remote',499.00,'assets/images/products/pcs/pc-1015.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1016','MSI Aegis RS (Tower) Gaming Desktop','Intel Core i7-12700KF, GeForce RTX 3060 Ti, 16GB Memory (Dual-CHL), 1TB SSD, WiFi 6E, Liquid Cooling, USB Type-C, VR-Ready, Win11H (12TG-261US) ',1999.99,'assets/images/products/pcs/pc-1016.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1017','Dell Inspiron G5 5000 Gaming Desktop Tower','Intel Core i7-10700F, 16GB DDR4 RAM, 1TB SSD, NVIDIA GeForce RTX 3060 12GB GDDR6, Windows 10 Home - Abyss Black (Latest Model',1647.49,'assets/images/products/pcs/pc-1017.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1018','Skytech Blaze ll Gaming PC Desktop','Intel i5-10400F, GTX 1660, 1TB NVME, 16G DDR4 3200, AC Wi-Fi, Windows 10 Home 64-bit, Black ',1093.60,'assets/images/products/pcs/pc-1018.jpg',1,5,NOW(),2);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PC-1019','Skytech Archangel Gaming Computer PC Desktop','Ryzen 5 3600 3.6GHz, GTX 1660 6G, 500GB SSD, 8GB DDR4 3200MHz, RGB Fans, Windows 10 Home 64-bit, 802.11AC Wi-Fi',1049.99,'assets/images/products/pcs/pc-1019.jpg',1,5,NOW(),2);



-- -----------------------------------------------------
-- Graphic Cards
-- ----------------------------------------------------
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1000','MSI Gaming GeForce RTX 3050 8GB','GDRR6 128-Bit HDMI/DP PCIe 4 Torx Twin Fans Ampere OC Graphics Card (RTX 3050 Ventus 2X 8G OC)',439.00,'assets/images/products/videocards/video-1000.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1001','EVGA GeForce RTX 2060 12GB','XC GAMING, 12G-P4-2263-KR, 12GB GDDR6, Dual Fans, Metal Backplate ',494.95,'assets/images/products/videocards/video-1001.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1002','XFX Speedster SWFT 210 Radeon','RX 6600 CORE Gaming Graphics Card with 8GB GDDR6 HDMI 3xDP, AMD RDNA 2 RX-66XL8LFDQ ',434.00,'assets/images/products/videocards/video-1002.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1003','GIGABYTE GeForce RTX 3080','Gaming OC 12G Graphics Card, 3X WINDFORCE Fans, 12GB 384-bit GDDR6X, GV-N3080GAMING OC-12GD Video Card ',1349.99,'assets/images/products/videocards/video-1003.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1004','ASUS Dual NVIDIA GeForce RTX 3050','OC Edition Gaming Graphics Card - PCIe 4.0, 8GB GDDR6 Memory, HDMI 2.1, DisplayPort 1.4a, 2-Slot Design, Axial-tech Fan Design, 0dB Technology, Steel Bracket',439.99,'assets/images/products/videocards/video-1004.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1005','MSI Geforce 210 1024 MB','DDR3 PCI-Express 2.0 Graphics Card MD1G/D3',57.99,'assets/images/products/videocards/video-1005.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1006','XFX Speedster QICK210 Radeon','RX 6500XT Black Gaming Graphics Card with 4GB GDDR6 HDMI , AMD RDNA 2 RX-65XT4DBDQ ',259.99,'assets/images/products/videocards/video-1006.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1007','GIGABYTE GeForce RTX 3060','Gaming OC 12G (REV2.0) Graphics Card, 3X WINDFORCE Fans, 12GB 192-bit GDDR6, GV-N3060GAMING OC-12GD REV2.0 Video Card',734.99,'assets/images/products/videocards/video-1007.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1008','GIGABYTE GeForce GT 730 2GB ','64-bit DDR3, GV-N730D3-2GI REV3.0 Graphic Cards',89.99,'assets/images/products/videocards/video-1008.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1009','MSI Gaming AMD Radeon RX 6600','128-bit 8GB GDDR6 DP/HDMI Dual Torx Fans FreeSync DirectX 12 VR Ready Graphics Card (RX 6600 MECH 2X 8G)',409.99,'assets/images/products/videocards/video-1009.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1010','ZOTAC GAMING GeForce GTX 1650','OC 4GB GDDR6 128-bit Gaming Graphics Card, Super Compact, ZT-T16520F-10L',304.60,'assets/images/products/videocards/video-1010.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1011','ASUS ROG Strix NVIDIA GeForce RTX 3050','OC Edition Gaming Graphics Card - PCIe 4.0, 8GB GDDR6, HDMI 2.1, DisplayPort 1.4a, Axial-tech Fan Design, 2.7-Slot, Super Alloy Power II, GPU Tweak II ',485.99,'assets/images/products/videocards/video-1011.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1012','MSI Gaming GeForce RTX 3080 Ti ','12GB GDRR6X 320-Bit HDMI/DP Nvlink Torx Fan 3 Ampere Architecture OC Graphics Card (RTX 3080 Ti Gaming X Trio 12G)',1924.99,'assets/images/products/videocards/video-1012.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1013','GIGABYTE GeForce RTX 3050','Eagle OC 8G Graphics Card, 2X WINDFORCE Fans, 8GB GDDR6 128-bit GDDR6, GV-N3050EAGLE OC-8GD Video Card',498.00,'assets/images/products/videocards/video-1013.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1014','MSI Gaming GeForce GTX 1650','128-Bit HDMI/DP/DVI 4GB GDRR6 HDCP Support DirectX 12 VR Ready OC Graphics Card (GTX 1650 D6 Ventus XS OC)',259.99,'assets/images/products/videocards/video-1014.jpg',1,5,NOW(),3);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('VIDEO-1015','ZOTAC GAMING GeForce GTX 1650','OC 4GB GDDR6 128-bit Gaming Graphics Card, Super Compact, ZT-T16520F-10L',318.92,'assets/images/products/videocards/video-1015.jpg',1,5,NOW(),3);




-- -----------------------------------------------------
-- Processors
-- -----------------------------------------------------
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1000','AMD Ryzen 9 5900X','12-core, 24-Thread Unlocked Desktop Processor',569.99,'assets/images/products/processors/proces-1000.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1001','AMD Ryzen 7 5800X','8-core, 16-Thread Unlocked Desktop Processor',449.00,'assets/images/products/processors/proces-1001.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1002','Intel Core i5-10400','Desktop Processor 6 Cores up to 4.3 GHz  LGA1200 (Intel 400 Series Chipset) 65W, Model Number: BX8070110400',182.00,'assets/images/products/processors/proces-1002.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1003','AMD Ryzen 5 5600G','6-Core 12-Thread Unlocked Desktop Processor with Radeon Graphics',209.99,'assets/images/products/processors/proces-1003.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1004','AMD Ryzen 5 5600X','6-core, 12-Thread Unlocked Desktop Processor with Wraith Stealth Cooler',228.98,'assets/images/products/processors/proces-1004.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1005','Intel Core i7-12700KF','Desktop Processor 12 (8P+4E) Cores up to 5.0 GHz Unlocked  LGA1700 600 Series Chipset 125W',465.00,'assets/images/products/processors/proces-1005.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1006','AMD Ryzen 7 3700X','8-Core, 16-Thread Unlocked Desktop Processor with Wraith Prism LED Cooler',364.99,'assets/images/products/processors/proces-1006.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1007','Intel® Core™ i7-11700K','Desktop Processor 8 Cores up to 5.0 GHz Unlocked LGA1200 (Intel 500 Series & Select 400 Series Chipset) 125W',344.99,'assets/images/products/processors/proces-1007.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1008','Intel® Core™ i9-10850K','Desktop Processor 10 Cores up to 5.2 GHz Unlocked LGA1200 (Intel® 400 Series chipset) 125W ',539.94,'assets/images/products/processors/proces-1008.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1009','Intel Core i7-10700KF','Desktop Processor 8 Cores up to 5.1 GHz Unlocked Without Processor Graphics LGA1200 (Intel 400 Series chipset) 125W ',361.00,'assets/images/products/processors/proces-1009.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1010','AMD Ryzen 9 5950X','16-core, 32-Thread Unlocked Desktop Processor',799.00,'assets/images/products/processors/proces-1010.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1011','Intel Core i9-11900K','Desktop Processor 8 Cores up to 5.3 GHz Unlocked LGA1200 (Intel 500 Series & Select 400 Series Chipset) 125W',439.86,'assets/images/products/processors/proces-1011.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1012','Intel Core i9-12900KF','Desktop Processor 16 (8P+8E) Cores up to 5.2 GHz Unlocked  LGA1700 600 Series Chipset 125W',676.25,'assets/images/products/processors/proces-1012.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1013','Intel Core i9-10900K','Desktop Processor 10 Cores up to 5.3 GHz Unlocked  LGA1200 (Intel 400 Series Chipset) 125W',499.00,'assets/images/products/processors/proces-1013.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1014','Intel® Core™ i5-9400F','Desktop Processor 6 Cores 4.1 GHz Turbo Without Graphics ',159.45,'assets/images/products/processors/proces-1014.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1015','AMD Ryzen 5 2600','Processor with Wraith Stealth Cooler - YD2600BBAFBOX',339.99,'assets/images/products/processors/proces-1015.jpg',1,5,NOW(),4);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('PROCES-1016','Intel Core i7-10700K','Desktop Processor 8 Cores up to 5.1 GHz Unlocked LGA1200 (Intel 400 Series Chipset) 125W (BX8070110700K) ',387.00,'assets/images/products/processors/proces-1016.jpg',1,5,NOW(),4);

-- -----------------------------------------------------
-- RAM
-- -----------------------------------------------------
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1000','Corsair Vengeance LPX 16GB','(2x8GB) DDR4 DRAM 3200MHz C16 Desktop Memory Kit - Black (CMK16GX4M2B3200C16)',77.99,'assets/images/products/rams/ram-1000.jpg',1,5,NOW(),5);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1001','Corsair Vengeance RGB PRO','16GB (2x8GB) DDR4 3200MHz C16 LED Desktop Memory - Black',91.99,'assets/images/products/rams/ram-1001.jpg',1,5,NOW(),5);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1002','Corsair Vengeance RGB Pro','32GB (2x16GB) DDR4 3200 (PC4-25600) C16 Desktop Memory – Black',154.99,'assets/images/products/rams/ram-1002.jpg',1,5,NOW(),5);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1003','TEAMGROUP T-Force Vulcan Z','DDR4 16GB Kit (2x8GB) 3000MHz (PC4-24000) CL16 Desktop Memory Module Ram (Gray) - TLZGD416G3000HC16CDC01',56.99,'assets/images/products/rams/ram-1003.jpg',1,5,NOW(),5);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1004','TEAMGROUP T-Force Delta RGB','DDR4 16GB (2x8GB) 3000MHz (PC4-24000) CL16 Desktop Memory Module Ram - White - TF4D416G3000HC16CDC01',69.99,'assets/images/products/rams/ram-1004.jpg',1,5,NOW(),5);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1005','Yongxinsheng DDR3 8GBx2','(16GB Kit) 1600MHz UDIMM RAM PC3-12800U CL11 240 Pins 1.5V Non-ECC Unbuffered Ddr3 Desktop Memory',54.95,'assets/images/products/rams/ram-1005.jpg',1,5,NOW(),5);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1006','G.Skill Trident Z NEO Series 32GB','(2 x 16GB) 288-Pin SDRAM PC4-28800 DDR4 3600 CL18-22-22-42 1.35V Dual Channel Desktop Memory Model F4-3600C18D-32GTZN ',159.99,'assets/images/products/rams/ram-1006.jpg',1,5,NOW(),5);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1007','Patriot 16GB(2x8GB) Viper III DDR3','1866MHz (PC3 15000) CL10 Desktop Memory with Black Mamba Heatsink - PV316G186C0K ',56.69,'assets/images/products/rams/ram-1007.jpg',1,5,NOW(),5);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1008','Crucial Ballistix 3200 MHz','DDR4 DRAM Desktop Gaming Memory Kit 32GB (16GBx2) CL16 BL2K16G32C16U4B (Black)',138.99,'assets/images/products/rams/ram-1008.jpg',1,5,NOW(),5);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('RAM-1009','TEAMGROUP T-Create Classic 10L','DDR4 16GB Kit (2 x 8GB) 3200MHz (PC4 25600) CL22 Desktop Memory Module Ram - TTCCD416G3200HC22DC01',56.99,'assets/images/products/rams/ram-1009.jpg',1,5,NOW(),5);

-- -----------------------------------------------------
-- Monitors
-- -----------------------------------------------------
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1000','Sceptre 24" Professional Thin 75Hz ','1080p LED Monitor 2x HDMI VGA Build-in Speakers, Machine Black (E248W-19203R Series)',134.99,'assets/images/products/monitors/monitor-1000.jpg',1,5,NOW(),6);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1001','SAMSUNG Odyssey G3 Series 27-Inch','FHD 1080p Gaming Monitor, 144Hz, 1ms, 3-Sided Border-Less, VESA Compatible, Height Adjustable Stand, FreeSync Premium (LF27G35TFBNXZA)',269.99,'assets/images/products/monitors/monitor-1001.jpg',1,5,NOW(),6);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1002','Acer SB220Q bi 21.5 Inches','Full HD (1920 x 1080) IPS Ultra-Thin Zero Frame Monitor (HDMI & VGA Port), Black',129.99,'assets/images/products/monitors/monitor-1002.jpg',1,5,NOW(),6);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1003','Sceptre 20" 1600 x 900 75Hz','LED Monitor 2X HDMI VGA Built-in Speakers, sRGB 99% Machine Black (E209W-16003RT Series)',115.63,'assets/images/products/monitors/monitor-1003.jpg',1,5,NOW(),6);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1004','LG 32ML600M-B 32” Inch','Full HD IPS LED Monitor with HDR 10 - Black',249.99,'assets/images/products/monitors/monitor-1004.jpg',1,5,NOW(),6);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1005','Acer K202HQL Abi 19.5"','HD Monitor (HDMI & VGA port), Black, 19.5 Inch',110.95,'assets/images/products/monitors/monitor-1005.jpg',1,5,NOW(),6);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1006','Sceptre E225W-19203R 22"','Ultra Thin 75Hz 1080p LED Monitor 2x HDMI VGA Build-in Speakers, Metallic Black 2018',130.35,'assets/images/products/monitors/monitor-1006.jpg',1,5,NOW(),6);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1007','ASUS VL249HE 23.8”','Eye Care Monitor, 1080P Full HD, 75Hz, IPS, Adaptive-Sync/FreeSync, Eye Care, HDMI VGA, Frameless Slim Design, VESA Wall Mountable ',144.99,'assets/images/products/monitors/monitor-1007.jpg',1,5,NOW(),6);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1008','SAMSUNG S80A Series 27-Inch 4K','UHD (3840x2160) Computer Monitor, HDMI, DP, USB Hub with USB-C, HDR10 (1 Billion Colors), Built-in Speakers, Fully Adjustable Stand with Pivot (LS27A800UNNXZA)',399.99,'assets/images/products/monitors/monitor-1008.jpg',1,5,NOW(),6);
INSERT INTO product(bar_code,name, description, unit_price, image_url, active, units_in_stock, date_created, category_id) VALUES ('MONITOR-1009','LG 24MP400-B 24” Full HD','(1920 x 1080) IPS Display with 3-Side Virtually Borderless Design, AMD FreeSync and OnScreen Control – Black ',209.90,'assets/images/products/monitors/monitor-1009.jpg',1,5,NOW(),6);



